<!--
To change this template, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
    </head>
    <body>
        qwwwwwwq
        
        <?php foreach ($products as $product) : ?>
            <?php var_dump($product); 
//            exit(1); 
            ?>
        <?php endforeach; ?>
        
    </body>
</html>
